module.exports = {
    INCREASE: 'INCREASE',
    DECREASE: 'DECREASE',
    ALL_TODOS: 'ALL_TODOS',
    EDIT_TODO: 'EDIT_TODO',
    CREATE_TODO: 'CREATE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    SINGLE_TODO: 'SINGLE_TODO',
    SEARCH_TODOS: 'SEARCH_TODOS',
    GET_GREETING: 'GET_GREETING',
};